# Form implementation generated from reading ui file 'welcome_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 439)
        MainWindow.setMinimumSize(QtCore.QSize(942, 439))
        MainWindow.setMaximumSize(QtCore.QSize(942, 439))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomeScreen_mainLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.welcomeScreen_mainLabel.setFont(font)
        self.welcomeScreen_mainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcomeScreen_mainLabel.setObjectName("welcomeScreen_mainLabel")
        self.verticalLayout.addWidget(self.welcomeScreen_mainLabel)
        self.welcomeScreen_infoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.welcomeScreen_infoLabel.setFont(font)
        self.welcomeScreen_infoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcomeScreen_infoLabel.setObjectName("welcomeScreen_infoLabel")
        self.verticalLayout.addWidget(self.welcomeScreen_infoLabel)
        self.returning_userButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.returning_userButton.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.returning_userButton.setFont(font)
        self.returning_userButton.setObjectName("returning_userButton")
        self.verticalLayout.addWidget(self.returning_userButton)
        self.new_userButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.new_userButton.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.new_userButton.setFont(font)
        self.new_userButton.setObjectName("new_userButton")
        self.verticalLayout.addWidget(self.new_userButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeScreen_mainLabel.setText(_translate("MainWindow", "⭒˚.⋆ Final Test Score Calculator ⭒˚.⋆"))
        self.welcomeScreen_infoLabel.setText(_translate("MainWindow", "Calculate what grade you need to pass your class!"))
        self.returning_userButton.setText(_translate("MainWindow", "Returning User"))
        self.new_userButton.setText(_translate("MainWindow", "New User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
